# Generated by Django 5.0.6 on 2024-07-18 18:43

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/avatar.svg', upload_to=users.models.upload_path_handle),
        ),
    ]
