# Generated by Django 5.0.6 on 2024-07-19 11:18

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/avatar.svg', upload_to=users.models.upload_path_handle, validators=[users.models.file_size]),
        ),
    ]
