# Generated by Django 5.0.6 on 2024-07-19 10:43

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseclass_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='group',
            field=models.CharField(choices=[('GENERAL', 'General'), ('LECTURE', 'Lecture')], default='LECTURE', max_length=7),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='type',
            field=models.CharField(choices=[('FILE', 'File'), ('LINK', 'Link')], default='FILE', max_length=4),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.upload_file_path_handle),
        ),
    ]
