# Generated by Django 5.0.6 on 2024-07-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_fileupload_group_fileupload_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
