# Generated by Django 5.0.6 on 2024-07-19 11:18

import courses.models
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_fileupload_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.upload_file_path_handle, validators=[users.models.file_size]),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
