# Generated by Django 5.0.6 on 2024-07-20 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_notification_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='ForClass',
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='ForClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courseclass'),
        ),
    ]
