# Generated by Django 5.0.6 on 2024-07-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_notification_forclass_alter_notification_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
