# Generated by Django 5.0.6 on 2024-07-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_rename_date_create_notification_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_created',
            field=models.DateTimeField(editable=False),
        ),
    ]
