# Generated by Django 5.0.6 on 2024-08-02 16:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_assignment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
