# Generated by Django 5.0.7 on 2024-08-04 09:28

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_submission_date_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
