# Generated by Django 5.0.6 on 2024-08-07 12:02

import courses.models
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_notification_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='text',
        ),
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.upload_assignment_file_path_handle, validators=[users.models.file_size]),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_opened',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
