# Generated by Django 5.0.6 on 2024-08-13 14:32

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_assignment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grade_comment',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
