# Generated by Django 5.0.7 on 2024-08-27 01:55

import courses.models
import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_submission_grade_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
