# Generated by Django 5.0.6 on 2024-07-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Ho Chi Minh City', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='Viet Nam', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='inClass',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
