# Generated by Django 5.0.6 on 2024-07-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_birthday_user_city_user_country_user_inclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NONE', 'None')], default='NONE', max_length=6),
        ),
    ]
