# Generated by Django 5.0.6 on 2024-07-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_fileupload_comment_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
